### ISSUE TITLE
error

### ISSUE THREAD

**Issue by official-notfishvr** [gorilla-quest-mod/monkey-bindings#1]
Critical: Missing inline-hook
./extern/includes/beatsaber-hook/src/inline-hook/And64InlineHook.cpp
./extern/includes/beatsaber-hook/src/inline-hook/inlineHook.c
./extern/includes/beatsaber-hook/src/inline-hook/relocate.c
Task Failed, see output above

**Comment by official-notfishvr** [comment]
add me on discord notfishvr___

**Comment by M4LivesAgain** [comment]
> add me on discord notfishvr___

are you trying to mod on quest using an outdated codegen from like years ago? its pretty simple to update and then make an auth mod for it

**Comment by keganpowers34** [comment]
we never made any progress on trying to make gorilla tag quest modifiable again sorry
